# Generated by Django 3.1.5 on 2021-01-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
